CREATE TABLE `log_chat` (
  `message_id` int(12) NOT NULL AUTO_INCREMENT,
  `type` enum('ALL','SHOUT','TELL','PARTY','CLAN','GM','PETITION_PLAYER','PETITION_GM','TRADE','ALLIANCE','ANNOUNCEMENT','BOAT','L2FRIEND','MSNCHAT','PARTYMATCH_ROOM','PARTYROOM_COMMANDER','PARTYROOM_ALL','HERO_VOICE','CRITICAL_ANNOUNCE','SCREEN_ANNOUNCE','BATTLEFIELD','MPCC_ROOM') NOT NULL,
  `channel_id` int(12) NOT NULL,
  `sender` int(12) NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `message` text NOT NULL,
  PRIMARY KEY (`message_id`)
);